me_do_aluno = ('thiago', 'rafael', 'luan', 'andre', 'laysla','edvaldo', 'andreia', 'luan', 'kauan')
materia = ('calculo', 'corpo humano','historia do brasil', 'geografia do mundo')
profesor = ('andre', 'rafael', 'luan', 'thiiago')
curso =('matematica', 'ciências', 'historia', 'geografia') 
media = ('7.0', '8.0', '9.0', '10.0') 

nome_do_aluno = input("Digite o seu nome : ")
materia = input("Digite a materia : ")
professor = input("Digite o nome do professor : ") 
curso = input("Digite o nome do curso : ")